- Gemfile
- Gemfile.lock
- app/controllers/books_controller.rb
- app/views/books/index.html.erb
- app/views/layouts/_footer.html.erb
- app/views/layouts/_navbar.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- config/routes.rb
- db/seeds.rb
> Added partials

- Gemfile.lock
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
> Styled the device views user

- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/_footer.html.erb
- app/views/layouts/_navbar.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
> homepage css 2

- app/views/books/index.html.erb
- app/views/books/new.html.erb
- app/views/books/show.html.erb
> books views

- app/controllers/books_controller.rb
- app/controllers/rentals_controller.rb
- app/views/books/show.html.erb
- app/views/layouts/_navbar.html.erb
- app/views/rentals/index.html.erb
- app/views/rentals/new.html.erb
- config/routes.rb
> This commits updates on rentals and general routes

- app/views/books/index.html.erb
- app/views/layouts/_navbar.html.erb
> updated navbar links, added Logo which directs to homepage

- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
> homepage image body

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_login.scss
- app/assets/stylesheets/pages/_signup.scss
- app/views/books/index.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/pages/home.html.erb
> edited books index, formatted cards, added search bar, formatted buttons

- app/controllers/books_controller.rb
- app/views/books/edit.html.erb
- app/views/books/new.html.erb
- app/views/books/show.html.erb
- app/views/layouts/_calendar.html.erb
- config/routes.rb
> view page of the book with calendar

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_login.scss
- app/assets/stylesheets/pages/_signup.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
> style-home-banner-buttons-font.

- app/controllers/rentals_controller.rb
- app/views/books/show.html.erb
- app/views/rentals/index.html.erb
> if statement images

- app/controllers/books_controller.rb
- app/views/books/show.html.erb
> delete method for books

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/views/layouts/_footer.html.erb
- app/views/layouts/application.html.erb
> working-on-footer

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/pages/_books_index.scss
- app/models/book.rb
- app/views/books/index.html.erb
- app/views/layouts/application.html.erb
> working on search function, logic not working

- app/assets/stylesheets/components/_footer.scss
- app/views/layouts/_footer.html.erb
- app/views/layouts/_navbar.html.erb
> added footer and some dropdown on the navbar

- app/views/pages/home.html.erb
> homepage design

- db/seeds.rb
> api added, and figured out how to read - from nyt

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_new.scss
- app/views/books/index.html.erb
- app/views/books/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/rentals/edit.html.erb
> add a book css

- app/views/books/index.html.erb
- app/views/books/show.html.erb
- db/seeds.rb
> working api, seeded fake users, added accounts for all team members

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_small_card.scss
- app/assets/stylesheets/pages/_books_index.scss
- app/views/books/index.html.erb
- app/views/books/show.html.erb
- app/views/layouts/_navbar.html.erb
- app/views/layouts/_small_card.html.erb
- app/views/rentals/index.html.erb
> Rentals index start

- app/controllers/books_controller.rb
- app/controllers/pages_controller.rb
- app/views/layouts/application.html.erb
- app/views/pages/profile.html.erb
> This commits updates on profile dashboard

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/pages/_books_index.scss
- app/assets/stylesheets/pages/_books_show.scss
- app/assets/stylesheets/pages/_login.scss
- app/views/books/edit.html.erb
- app/views/books/index.html.erb
- app/views/books/show.html.erb
- db/migrate/20230602103922_add_first_name_to_users.rb
> css design still in progress
